# Generated by Django 5.2.11 on 2026-02-20 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epstein_ui', '0013_add_comment_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=16)),
                ('parameters', models.JSONField(default=dict)),
                ('total_documents', models.IntegerField(default=0)),
                ('total_pages', models.IntegerField(default=0)),
                ('total_redactions', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(db_index=True, max_length=255)),
                ('file_path', models.TextField()),
                ('total_pages', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('pdf_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_documents', to='epstein_ui.pdfdocument')),
                ('extraction_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_documents', to='epstein_ui.extractionrun')),
            ],
        ),
        migrations.CreateModel(
            name='RedactionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_num', models.IntegerField()),
                ('redaction_index', models.IntegerField()),
                ('bbox_x0_points', models.FloatField()),
                ('bbox_y0_points', models.FloatField()),
                ('bbox_x1_points', models.FloatField()),
                ('bbox_y1_points', models.FloatField()),
                ('width_points', models.FloatField()),
                ('height_points', models.FloatField()),
                ('bbox_x0_pixels', models.IntegerField()),
                ('bbox_y0_pixels', models.IntegerField()),
                ('bbox_x1_pixels', models.IntegerField()),
                ('bbox_y1_pixels', models.IntegerField()),
                ('width_pixels', models.IntegerField()),
                ('height_pixels', models.IntegerField()),
                ('detection_method', models.CharField(db_index=True, max_length=16)),
                ('confidence', models.FloatField(db_index=True)),
                ('estimated_chars', models.IntegerField(db_index=True, default=0)),
                ('font_size_nearby', models.FloatField(blank=True, null=True)),
                ('avg_char_width', models.FloatField(blank=True, null=True)),
                ('text_before', models.TextField(blank=True)),
                ('text_after', models.TextField(blank=True)),
                ('has_ascender_leakage', models.BooleanField(default=False)),
                ('has_descender_leakage', models.BooleanField(default=False)),
                ('leakage_pixels_top', models.IntegerField(default=0)),
                ('leakage_pixels_bottom', models.IntegerField(default=0)),
                ('is_multiline', models.BooleanField(default=False)),
                ('multiline_group_id', models.CharField(blank=True, max_length=255)),
                ('line_index_in_group', models.IntegerField(blank=True, null=True)),
                ('image_tight', models.TextField(blank=True)),
                ('image_context', models.TextField(blank=True)),
                ('extracted_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redactions', to='epstein_ui.extracteddocument')),
            ],
        ),
        migrations.AddIndex(
            model_name='extracteddocument',
            index=models.Index(fields=['extraction_run', 'doc_id'], name='epstein_ui__extract_4fdea7_idx'),
        ),
        migrations.AddIndex(
            model_name='redactionrecord',
            index=models.Index(fields=['extracted_document', 'page_num'], name='epstein_ui__extract_4eae4d_idx'),
        ),
        migrations.AddIndex(
            model_name='redactionrecord',
            index=models.Index(fields=['detection_method', 'estimated_chars'], name='epstein_ui__detecti_8079b4_idx'),
        ),
    ]
