# Generated by Django 5.2.11 on 2026-02-21 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epstein_ui', '0016_documententity_candidatelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_redactions', models.IntegerField(default=0)),
                ('processed', models.IntegerField(default=0)),
                ('total_matches', models.IntegerField(default=0)),
                ('status', models.CharField(default='running', max_length=16)),
                ('font_identified_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RedactionCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_text', models.CharField(max_length=512)),
                ('total_score', models.FloatField(db_index=True)),
                ('width_fit', models.FloatField(default=0)),
                ('nlp_score', models.FloatField(default=0)),
                ('leakage_score', models.FloatField(default=0)),
                ('corpus_freq', models.FloatField(default=0)),
                ('doc_freq', models.FloatField(default=0)),
                ('width_ratio', models.FloatField(default=0, help_text='candidate_width / redaction_width')),
                ('rank', models.IntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['redaction', 'rank'],
            },
        ),
        migrations.RenameIndex(
            model_name='documententity',
            new_name='epstein_ui__entity__389e76_idx',
            old_name='epstein_ui_do_entity__4c0c3e_idx',
        ),
        migrations.RenameIndex(
            model_name='documententity',
            new_name='epstein_ui__extract_4a81b6_idx',
            old_name='epstein_ui_do_extract_8f1a2b_idx',
        ),
        migrations.AddField(
            model_name='redactioncandidate',
            name='redaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='epstein_ui.redactionrecord'),
        ),
        migrations.AddIndex(
            model_name='redactioncandidate',
            index=models.Index(fields=['redaction', 'rank'], name='epstein_ui__redacti_d46209_idx'),
        ),
        migrations.AddIndex(
            model_name='redactioncandidate',
            index=models.Index(fields=['candidate_text'], name='epstein_ui__candida_a5cbe4_idx'),
        ),
    ]
